// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Oracle.EntityFrameworkCore.Metadata;

namespace ModbusMaster.DAL.Migrations.Data
{
    [DbContext(typeof(ModbusDumpContext))]
    partial class ModbusDumpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Baudrate")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ComPort")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Parity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("StopBits")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte?>("Identificator")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Ip")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelId = 1,
                            Ip = "127.0.0.1",
                            Port = 502,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ChannelId = 1,
                            Ip = "127.0.0.2",
                            Port = 502,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Dump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Data")
                        .HasColumnType("NUMBER(5)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Offset")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("RegisterType")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Dumps");
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Formula")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Offset")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 5,
                            DeviceId = 1,
                            Offset = 0,
                            Type = 20001
                        },
                        new
                        {
                            Id = 2,
                            Count = 3,
                            DeviceId = 2,
                            Offset = 0,
                            Type = 10001
                        });
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Device", b =>
                {
                    b.HasOne("ModbusMaster.Domain.Entities.Channel", "Channel")
                        .WithMany("Devices")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Dump", b =>
                {
                    b.HasOne("ModbusMaster.Domain.Entities.Device", "Device")
                        .WithMany("Dumps")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusMaster.Domain.Entities.Register", b =>
                {
                    b.HasOne("ModbusMaster.Domain.Entities.Device", "Device")
                        .WithMany("Registers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
