// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModbusMaster.Client.DAL;
using Oracle.EntityFrameworkCore.Metadata;

namespace ModbusMaster.Client.DAL.Migrations.Client
{
    [DbContext(typeof(ModbusClientContext))]
    partial class ModbusClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.ChannelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Baudrate")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ComPort")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Parity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("StopBits")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.DeviceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte?>("Identificator")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Ip")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.DumpConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Data")
                        .HasColumnType("NUMBER(5)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Offset")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("RegisterType")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Dumps");
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.RegisterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Formula")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Offset")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.DeviceConfig", b =>
                {
                    b.HasOne("ModbusMaster.Client.Domain.Entities.ChannelConfig", "Channel")
                        .WithMany("Devices")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.DumpConfig", b =>
                {
                    b.HasOne("ModbusMaster.Client.Domain.Entities.DeviceConfig", "Device")
                        .WithMany("Dumps")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusMaster.Client.Domain.Entities.RegisterConfig", b =>
                {
                    b.HasOne("ModbusMaster.Client.Domain.Entities.DeviceConfig", "Device")
                        .WithMany("Registers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
